---
abstract: 'Round trip simple name/value config file handling.'
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::CheckDeps: 0
  Test::File: 0
  Test::File::Contents: 0
  Test::More: 0.94
  Test::Most: 0
  Test::NoWarnings: 0
  Test::Requires: 0
  Test::UseAllModules: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-NameValue
requires:
  Carp: 0
  File::Slurp: 0
  IO::Handle: 0
  POSIX: 0
  Scalar::Util: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources: {}
version: 1.01
